-- ============================================================================
-- LESSON TRANSLATIONS (Russian)
-- ============================================================================

INSERT INTO lesson_translation (lesson_id, language_code, lesson_name)
VALUES (1, 'ru', 'Обучение'),
       (2, 'ru', 'Кнопки (JButton)'),
       (3, 'ru', 'Метки (JLabel)'),
       (4, 'ru', 'Текстовые поля (JTextField)'),
       (5, 'ru', 'Текстовые области (JTextArea)'),
       (6, 'ru', 'Поля паролей (JPasswordField)'),
       (7, 'ru', 'Флажки (JCheckBox)'),
       (8, 'ru', 'Радиокнопки (JRadioButton)'),
       (9, 'ru', 'Переключатели (JToggleButton)'),
       (10, 'ru', 'Выпадающие списки (JComboBox)'),
       (11, 'ru', 'Списки (JList)'),
       (12, 'ru', 'Слайдеры (JSlider)'),
       (13, 'ru', 'Спиннеры (JSpinner)'),
       (14, 'ru', 'Индикаторы прогресса (JProgressBar)'),
       (15, 'ru', 'Полосы прокрутки (JScrollBar)'),
       (16, 'ru', 'Панели (JPanel)'),
       (17, 'ru', 'Окна (JFrame)'),
       (18, 'ru', 'Диалоговые окна (JDialog)'),
       (19, 'ru', 'Окна (JWindow)'),
       (20, 'ru', 'Панели с прокруткой (JScrollPane)'),
       (21, 'ru', 'Разделённые панели (JSplitPane)'),
       (22, 'ru', 'Вкладки (JTabbedPane)'),
       (23, 'ru', 'Панели инструментов (JToolBar)'),
       (24, 'ru', 'Строки меню (JMenuBar)'),
       (25, 'ru', 'Меню (JMenu)'),
       (26, 'ru', 'Пункты меню (JMenuItem)'),
       (27, 'ru', 'Флажки в меню (JCheckBoxMenuItem)'),
       (28, 'ru', 'Swing: Радиокнопки в меню (JRadioButtonMenuItem)'),
       (29, 'ru', 'Swing: Всплывающие меню (JPopupMenu)'),
       (30, 'ru', 'Таблицы (JTable)'),
       (31, 'ru', 'Деревья (JTree)'),
       (32, 'ru', 'Редактор HTML/RTF (JEditorPane)'),
       (33, 'ru', 'Расширенный редактор (JTextPane)'),
       (34, 'ru', 'Диалоговые окна (JOptionPane)'),
       (35, 'ru', 'Выбор файлов (JFileChooser)'),
       (36, 'ru', 'Выбор цвета (JColorChooser)'),
       (37, 'ru', 'BorderLayout - Компоновка по краям'),
       (38, 'ru', 'FlowLayout - Компоновка в ряд'),
       (39, 'ru', 'GridLayout - Компоновка в сетке'),
       (40, 'ru', 'GridBagLayout - Гибкая сетка'),
       (41, 'ru', 'BoxLayout - Вертикальная/горизонтальная компоновка'),
       (42, 'ru', 'CardLayout - Переключение панелей'),
       (43, 'ru', 'GroupLayout - Групповая компоновка'),
       (44, 'ru', 'SpringLayout - Пружинная компоновка'),
       (45, 'ru', 'ActionListener - Обработка действий'),
       (46, 'ru', 'MouseListener - Обработка событий мыши'),
       (47, 'ru', 'KeyListener - Обработка клавиатуры'),
       (48, 'ru', 'FocusListener - Обработка фокуса'),
       (49, 'ru', 'ItemListener и ChangeListener - Обработка выбора и изменений'),
       (50, 'ru', 'Кастомная отрисовка (paintComponent)'),
       (51, 'ru', 'Кастомные компоненты (Custom Components)'),
       (52, 'ru', 'Look and Feel - Внешний вид'),
       (53, 'ru', 'Timer - Таймеры');
